namespace Moq.Microsoft.Configuration.Tests.SourceGenerators.Enums
{
	internal enum TestType : byte
	{
		Bool,
		BoolNullable,
		Char,
		CharNullable,
		Int,
		IntNullable,
		IntUnsigned,
		IntUnsignedNullable,
		Byte,
		ByteNullable,
		SignedByte,
		ByteSignedNullable,
		Short,
		ShortNullable,
		ShortUnsigned,
		ShortUnsignedNullable,
		Long,
		LongNullable,
		LongUnsigned,
		LongUnsignedNullable,
		Decimal,
		DecimalNullable,
		Double,
		DoubleNullable,
		Float,
		FloatNullable,
		String
	}
}
