name: Build Moq.Microsoft.Configuration

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]
  workflow_dispatch:
    
env:
  Configuration: RELEASE
  ArtifactsName: nuget

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Install .NET7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    
    - name: NuGet restore
      run: dotnet restore
    
    - name: Build
      run: dotnet build -c ${{ env.Configuration }} --no-restore
    
    - name: Run tests
      run: dotnet test -c ${{ env.Configuration }} -v m --no-restore --no-build
      
    - name: Create NuGet Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: ${{ env.ArtifactsName }}
        path: '**/*.nupkg'

  release:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.event.pull_request.labels.*.name, 'release') && github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Download NuGet Artifacts
      uses: actions/download-artifact@v2.0.10
      with:
        name: ${{ env.ArtifactsName }}
        
    - name: NuGet push
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}
        NUGET_SOURCE_URL: https://api.nuget.org/v3/index.json
      run: dotnet nuget push -s ${{ env.NUGET_SOURCE_URL }} -k ${{ env.NUGET_AUTH_TOKEN }} **/*.nupkg
